name: Build, Push, Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- backend ---
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            eugene8pro/django_avant:2.0
            eugene8pro/django_avant:latest

      # --- nginx ---
      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: |
            eugene8pro/nginx_avant:2.0
            eugene8pro/nginx_avant:latest
          build-args: |
            VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -euxo pipefail

            cd /opt/apps/avant_garde_at_war

            # stop/remove containers (but keep ./data)
            docker compose down --remove-orphans

            # remove old local images (ignore if missing)
            docker image rm -f \
              eugene8pro/django_avant:2.0 \
              eugene8pro/django_avant:latest \
              eugene8pro/nginx_avant:2.0 \
              eugene8pro/nginx_avant:latest \
              || true

            # pull latest images referenced by docker-compose.yml
            docker compose pull

            # start fresh
            docker compose up -d

            docker compose ps

            # cleanup dangling layers etc.
            docker image prune -f
