# Generated by Django 6.0.1 on 2026-01-26 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EuPro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_name", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField(max_length=65535)),
                ("date_of_writing", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "eu_pro",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RawVerses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_name", models.CharField(max_length=50)),
                ("title", models.TextField(null=True)),
                ("text", models.TextField(max_length=50000, null=True)),
                ("date_of_writing", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "raw_verses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
                ("html_name", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hermeneutics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_name", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField(max_length=65535)),
                ("date_of_writing", models.DateField(blank=True, null=True)),
                (
                    "raw_verses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="avantgarde.rawverses",
                    ),
                ),
            ],
            options={
                "db_table": "hermeneutics",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_name", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("audio", models.FileField(blank=True, null=True, upload_to="audio/")),
                ("date_of_writing", models.DateField(blank=True, null=True)),
                (
                    "raw_verses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="avantgarde.rawverses",
                    ),
                ),
            ],
            options={
                "db_table": "audio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AnswerToReclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
                ("repeat", models.PositiveIntegerField(default=100)),
                (
                    "reclamation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="avantgarde.reclamation",
                    ),
                ),
            ],
        ),
    ]
