# Generated by Django 6.0.1 on 2026-01-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RawVerses",
            new_name="RawVerse",
        ),
    ]
