# Generated by Django 6.0.1 on 2026-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0002_rename_rawverses_rawverse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawverse",
            name="title",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
