# Generated by Django 6.0.1 on 2026-01-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0003_alter_rawverse_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawverse",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
