# Generated by Django 6.0.1 on 2026-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0004_rawverse_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawverse",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
