# Generated by Django 6.0.1 on 2026-01-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0005_alter_rawverse_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawverse",
            name="html_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
