# Generated by Django 6.0.1 on 2026-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0006_alter_rawverse_html_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
