# Generated by Django 6.0.1 on 2026-02-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0007_alter_audio_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="HermRandVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
                ("html_name", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
