# Generated by Django 6.0.1 on 2026-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0008_hermrandverse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="text",
            field=models.CharField(default="", max_length=30),
        ),
    ]
