# Generated by Django 6.0.1 on 2026-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0009_alter_reclamation_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
