# Generated by Django 6.0.1 on 2026-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0010_contentorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentorder",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
