# Generated by Django 6.0.1 on 2026-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0011_contentorder_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentorder",
            name="html_name",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
