# Generated by Django 6.0.1 on 2026-02-13 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0012_contentorder_html_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentorder",
            name="html_name",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
