# Generated by Django 6.0.1 on 2026-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0013_alter_contentorder_html_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawverse",
            name="html_name",
            field=models.SlugField(unique=True),
        ),
    ]
