# Generated by Django 6.0.1 on 2026-02-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0014_alter_rawverse_html_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="html_name",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="eupro",
            name="html_name",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hermeneutics",
            name="html_name",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
