# Generated by Django 6.0.1 on 2026-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0015_alter_audio_html_name_alter_eupro_html_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "year",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "word_of_year",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("html_name", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
