# Generated by Django 6.0.1 on 2026-02-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0016_historytime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historytime",
            name="html_name",
        ),
    ]
