# Generated by Django 6.0.1 on 2026-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0017_remove_historytime_html_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historytime",
            name="herm",
            field=models.TextField(default=""),
        ),
    ]
