# Generated by Django 6.0.1 on 2026-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0018_historytime_herm"),
    ]

    operations = [
        migrations.AddField(
            model_name="historytime",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
