# Generated by Django 6.0.1 on 2026-02-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0019_historytime_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historytime",
            name="herm",
        ),
        migrations.RemoveField(
            model_name="historytime",
            name="title",
        ),
    ]
