# Generated by Django 6.0.1 on 2026-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0020_remove_historytime_herm_remove_historytime_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HermToHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="eupro",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="eupro",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
