# Generated by Django 6.0.1 on 2026-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0021_hermtohistory_alter_eupro_text_alter_eupro_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentorder",
            name="qr_text",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
