# Generated by Django 6.0.1 on 2026-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0023_hermtomakecopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentorder",
            name="html_for_qr",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
