# Generated by Django 6.0.1 on 2026-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0024_contentorder_html_for_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentorder",
            name="html_for_qr",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
