# Generated by Django 6.0.1 on 2026-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0025_alter_contentorder_html_for_qr"),
    ]

    operations = [
        migrations.CreateModel(
            name="HermToQrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("text", models.TextField()),
            ],
        ),
    ]
