# Generated by Django 6.0.1 on 2026-09-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0026_hermtoqrcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EuPro",
        ),
    ]
