# Generated by Django 6.0.1 on 2026-09-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avantgarde", "0027_delete_eupro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answertoreclamation",
            name="reclamation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="avantgarde.reclamation",
            ),
        ),
    ]
